In [1]:
from pathlib import Path
import json
import sys

cwd = Path.cwd().resolve()
ROOT = next(p for p in (cwd, *cwd.parents) if (p / "AGENTS.md").is_file() and (p / "pyproject.toml").is_file())
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.model_evaluation.contract import ModelEvaluationConfig
from scripts.model_evaluation.pipeline import build_model_evaluation, run_summary

In [2]:
config = ModelEvaluationConfig(root=ROOT)
result = build_model_evaluation(config)

In [3]:
summary = run_summary(result, ROOT)
print(json.dumps({"model_evaluation_run": summary}, indent=2))

{
  "model_evaluation_run": {
    "status": "PASS",
    "model_evaluation_bundle": "artifacts/model_evaluation/7a4f36dc93ed1aba69ac00c6f086bf822f46bb2bfb640cd91dfde0ea4eebb257",
    "bundle_id": "7a4f36dc93ed1aba69ac00c6f086bf822f46bb2bfb640cd91dfde0ea4eebb257",
    "stage4_candidate_suite_bundle": "artifacts/model_training/candidate_suite/38bf0b7eb6e492feec1437d3782c7b528c787e78c63a016ed8499aa56e3dbfb2",
    "candidate_families": [
      "xgboost",
      "lightgbm",
      "gam"
    ],
    "calibration_selected": {
      "gam_2018-12_t1": "original",
      "gam_2018-12_t2": "original",
      "gam_2020-12_t1": "original",
      "gam_2020-12_t2": "sigmoid",
      "gam_2022-12_t1": "original",
      "gam_2022-12_t2": "original",
      "gam_2024-06_t1": "original",
      "gam_2024-06_t2": "original",
      "lightgbm_2018-12_t1": "original",
      "lightgbm_2018-12_t2": "original",
      "lightgbm_2020-12_t1": "original",
      "lightgbm_2020-12_t2": "sigmoid",
      "lightgbm_2022-12_t1": "original",
      "lightgbm_2022-12_t2": "original",
      "lightgbm_2024-06_t1": "original",
      "lightgbm_2024-06_t2": "original",
      "xgboost_2018-12_t1": "original",
      "xgboost_2018-12_t2": "original",
      "xgboost_2020-12_t1": "original",
      "xgboost_2020-12_t2": "sigmoid",
      "xgboost_2022-12_t1": "original",
      "xgboost_2022-12_t2": "original",
      "xgboost_2024-06_t1": "original",
      "xgboost_2024-06_t2": "original"
    },
    "threshold_status": {
      "gam_2018-12_t1": "selected",
      "gam_2018-12_t2": "selected",
      "gam_2020-12_t1": "selected",
      "gam_2020-12_t2": "selected",
      "gam_2022-12_t1": "selected",
      "gam_2022-12_t2": "selected",
      "gam_2024-06_t1": "selected",
      "gam_2024-06_t2": "selected",
      "lightgbm_2018-12_t1": "selected",
      "lightgbm_2018-12_t2": "selected",
      "lightgbm_2020-12_t1": "selected",
      "lightgbm_2020-12_t2": "selected",
      "lightgbm_2022-12_t1": "selected",
      "lightgbm_2022-12_t2": "selected",
      "lightgbm_2024-06_t1": "selected",
      "lightgbm_2024-06_t2": "selected",
      "xgboost_2018-12_t1": "selected",
      "xgboost_2018-12_t2": "selected",
      "xgboost_2020-12_t1": "selected",
      "xgboost_2020-12_t2": "selected",
      "xgboost_2022-12_t1": "selected",
      "xgboost_2022-12_t2": "selected",
      "xgboost_2024-06_t1": "selected",
      "xgboost_2024-06_t2": "selected"
    },
    "threshold_meets_gain": {
      "gam_2018-12_t1": true,
      "gam_2018-12_t2": false,
      "gam_2020-12_t1": true,
      "gam_2020-12_t2": true,
      "gam_2022-12_t1": true,
      "gam_2022-12_t2": true,
      "gam_2024-06_t1": true,
      "gam_2024-06_t2": true,
      "lightgbm_2018-12_t1": true,
      "lightgbm_2018-12_t2": true,
      "lightgbm_2020-12_t1": true,
      "lightgbm_2020-12_t2": true,
      "lightgbm_2022-12_t1": true,
      "lightgbm_2022-12_t2": true,
      "lightgbm_2024-06_t1": true,
      "lightgbm_2024-06_t2": true,
      "xgboost_2018-12_t1": true,
      "xgboost_2018-12_t2": false,
      "xgboost_2020-12_t1": true,
      "xgboost_2020-12_t2": true,
      "xgboost_2022-12_t1": true,
      "xgboost_2022-12_t2": true,
      "xgboost_2024-06_t1": true,
      "xgboost_2024-06_t2": true
    },
    "fit_counts": {
      "hyperparameter_models": 112,
      "internal_models": 24,
      "outer_models": 24,
      "sigmoid": 24,
      "total": 184
    },
    "development_rows": 21888,
    "posterior_rows": 10032,
    "knobs": {
      "max_false_alarm_increase_pp": 5.0,
      "min_onset_sensitivity_gain_pp": 10.0,
      "seed": 42
    },
    "determinism_limits": [
      "Stage5 verifies Stage4 identities and generates bounded earlier internal evidence from unchanged grids; historical late folds cannot establish this calibration calendar.",
      "Corrected Stage5 refits one outer model per candidate/window/horizon using fixed family grid and seed.",
      "Sigmoid calibration and threshold optimization are deterministic under fixed seed and stable dependencies.",
      "Notebook execution receipts depend on kernel package versions."
    ],
    "supersedes": {
      "note": "Prior bundles including PLAN026 are historical and superseded: origin-origin checks did not establish label availability. Original bundles and plan records remain untouched.",
      "stage5_bundle_ids": [
        "17b1d99f371b5aa6eb08ee45c8ce493fd599874f751981df0d1cfc117957eb98",
        "2367c0d165de3cdb6123dae2d03e04d2fd303ec18045524579da13f7dde2b8ff",
        "2bc97c66f0eccbaebc63c255b606dfe9956ac139df42584720131d812137d988",
        "8d14b2bedfff75e293cd43da6dd5cbf4f7706089ace06a3ead472ad911d9ba95",
        "acde04fffb283f1a48d68be57be3ec5b993bfdc76a19f8597df12e1dc66273d3",
        "c1e1ea31ac2bb36390d027551b659dee0dc06fc0f5b6b6adf83f87156b1c64eb",
        "ea5c2d8ce2128ed936f18b0119e9fb304dfdb0da518f467a2b0d17fe8640a605"
      ]
    }
  }
}

In [4]:
import pandas as pd
from IPython.display import display

calibration = pd.read_csv(result.bundle / "calibration_selection.csv")
thresholds = pd.read_csv(result.bundle / "threshold_selection.csv")
temporal_audit = pd.read_csv(result.bundle / "temporal_audit.csv")

display(calibration)
display(thresholds)

audit_flags = ["chronology_pass", "independence_pass", "component_available_pass", "no_reserved_pass"]
audit_view = temporal_audit[
    [
        "candidate",
        "window_id",
        "horizon",
        "selected_configuration_id",
        *audit_flags,
    ]
]
display(audit_view)

,candidate,window_id,horizon,alternative,selection_split,brier,rows,positives,supported_bins,supported_rows,weighted_absolute_gap
0,xgboost,2018-12_t1,1,original,calibration_selection,0.149339,152,35,2,107,0.019035
1,xgboost,2018-12_t1,1,sigmoid,calibration_selection,0.205859,152,35,1,152,0.170634
2,xgboost,2018-12_t2,2,original,calibration_selection,0.177092,152,35,2,104,0.065682
3,xgboost,2018-12_t2,2,sigmoid,calibration_selection,0.205777,152,35,1,152,0.171004
4,xgboost,2020-12_t1,1,original,calibration_selection,0.157861,152,28,2,70,0.056183
5,xgboost,2020-12_t1,1,sigmoid,calibration_selection,0.162491,152,28,1,68,0.145958
6,xgboost,2020-12_t2,2,original,calibration_selection,0.208709,152,28,2,62,0.160924
7,xgboost,2020-12_t2,2,sigmoid,calibration_selection,0.203837,152,28,3,125,0.214252
8,xgboost,2022-12_t1,1,original,calibration_selection,0.100352,152,41,2,88,0.060684
9,xgboost,2022-12_t1,1,sigmoid,calibration_selection,0.121053,152,41,1,100,0.033303
10,xgboost,2022-12_t2,2,original,calibration_selection,0.120339,152,41,3,106,0.035735
11,xgboost,2022-12_t2,2,sigmoid,calibration_selection,0.154717,152,41,1,109,0.017799
12,xgboost,2024-06_t1,1,original,calibration_selection,0.175987,152,76,0,0,NaN
13,xgboost,2024-06_t1,1,sigmoid,calibration_selection,0.186596,152,76,1,33,0.088611
14,xgboost,2024-06_t2,2,original,calibration_selection,0.198110,152,76,0,0,NaN
15,xgboost,2024-06_t2,2,sigmoid,calibration_selection,0.212873,152,76,1,44,0.002915
16,lightgbm,2018-12_t1,1,original,calibration_selection,0.148765,152,35,2,110,0.026822
17,lightgbm,2018-12_t1,1,sigmoid,calibration_selection,0.205979,152,35,1,152,0.170780
18,lightgbm,2018-12_t2,2,original,calibration_selection,0.177401,152,35,3,134,0.076797
19,lightgbm,2018-12_t2,2,sigmoid,calibration_selection,0.205710,152,35,1,152,0.171263
20,lightgbm,2020-12_t1,1,original,calibration_selection,0.153044,152,28,1,37,0.032307
21,lightgbm,2020-12_t1,1,sigmoid,calibration_selection,0.160395,152,28,2,97,0.176526
22,lightgbm,2020-12_t2,2,original,calibration_selection,0.216343,152,28,0,0,NaN
23,lightgbm,2020-12_t2,2,sigmoid,calibration_selection,0.207367,152,28,2,93,0.218829
24,lightgbm,2022-12_t1,1,original,calibration_selection,0.099713,152,41,2,85,0.056996
25,lightgbm,2022-12_t1,1,sigmoid,calibration_selection,0.119227,152,41,1,92,0.029027
26,lightgbm,2022-12_t2,2,original,calibration_selection,0.120379,152,41,2,77,0.048941
27,lightgbm,2022-12_t2,2,sigmoid,calibration_selection,0.156599,152,41,1,108,0.029268
28,lightgbm,2024-06_t1,1,original,calibration_selection,0.175918,152,76,0,0,NaN
29,lightgbm,2024-06_t1,1,sigmoid,calibration_selection,0.186323,152,76,1,35,0.054806
30,lightgbm,2024-06_t2,2,original,calibration_selection,0.199915,152,76,0,0,NaN
31,lightgbm,2024-06_t2,2,sigmoid,calibration_selection,0.215122,152,76,1,37,0.047090
32,gam,2018-12_t1,1,original,calibration_selection,0.156743,152,35,2,107,0.049021
33,gam,2018-12_t1,1,sigmoid,calibration_selection,0.205382,152,35,1,152,0.170086
34,gam,2018-12_t2,2,original,calibration_selection,0.177245,152,35,3,133,0.058652
35,gam,2018-12_t2,2,sigmoid,calibration_selection,0.205346,152,35,1,152,0.170069
36,gam,2020-12_t1,1,original,calibration_selection,0.168325,152,28,1,46,0.049607
37,gam,2020-12_t1,1,sigmoid,calibration_selection,0.180083,152,28,2,93,0.215973
38,gam,2020-12_t2,2,original,calibration_selection,0.246737,152,28,0,0,NaN
39,gam,2020-12_t2,2,sigmoid,calibration_selection,0.228049,152,28,3,131,0.287380
40,gam,2022-12_t1,1,original,calibration_selection,0.101427,152,41,2,89,0.045219
41,gam,2022-12_t1,1,sigmoid,calibration_selection,0.132532,152,41,1,103,0.042238
42,gam,2022-12_t2,2,original,calibration_selection,0.124090,152,41,2,79,0.042315
43,gam,2022-12_t2,2,sigmoid,calibration_selection,0.165914,152,41,1,108,0.022998
44,gam,2024-06_t1,1,original,calibration_selection,0.177314,152,76,0,0,NaN
45,gam,2024-06_t1,1,sigmoid,calibration_selection,0.184041,152,76,1,31,0.021717
46,gam,2024-06_t2,2,original,calibration_selection,0.201745,152,76,0,0,NaN
47,gam,2024-06_t2,2,sigmoid,calibration_selection,0.215040,152,76,2,76,0.082927

,candidate,window_id,horizon,selected_configuration_id,calibration_choice,calibration_reason,persistence_onset_sensitivity,persistence_false_alarm_ratio,max_allowed_false_alarm_ratio,min_required_onset_sensitivity,status,selected_threshold,meets_min_onset_gain,selected_onset_sensitivity,selected_false_alarm_ratio,selected_false_alerts,selected_emitted_alerts,feasible_threshold_count
0,xgboost,2018-12_t1,1,xgboost_00,original,brier_not_improved,0.000000,0.409091,0.459091,0.100000,selected,0.373360,True,0.235294,0.428571,21,49,51
1,xgboost,2018-12_t2,2,xgboost_00,original,brier_not_improved,0.352941,0.487805,0.537805,0.452941,selected,0.353250,False,0.294118,0.529412,27,51,34
2,xgboost,2020-12_t1,1,xgboost_02,original,brier_not_improved,0.000000,0.636364,0.686364,0.100000,selected,0.284780,True,0.357143,0.628571,22,35,37
3,xgboost,2020-12_t2,2,xgboost_00,sigmoid,brier_improved,0.214286,0.631579,0.681579,0.314286,selected,0.369002,True,0.500000,0.674419,29,43,20
4,xgboost,2022-12_t1,1,xgboost_04,original,brier_not_improved,0.000000,0.500000,0.550000,0.100000,selected,0.283434,True,0.200000,0.488372,21,43,44
5,xgboost,2022-12_t2,2,xgboost_02,original,brier_not_improved,0.266667,0.550000,0.600000,0.366667,selected,0.231101,True,0.666667,0.594203,41,69,67
6,xgboost,2024-06_t1,1,xgboost_01,original,brier_not_improved,0.000000,0.275862,0.325862,0.100000,selected,0.306253,True,0.294118,0.306122,30,98,97
7,xgboost,2024-06_t2,2,xgboost_01,original,brier_not_improved,0.294118,0.308642,0.358642,0.394118,selected,0.314686,True,0.588235,0.329897,32,97,103
8,lightgbm,2018-12_t1,1,lightgbm_00,original,brier_not_improved,0.000000,0.409091,0.459091,0.100000,selected,0.305642,True,0.235294,0.440000,22,50,48
9,lightgbm,2018-12_t2,2,lightgbm_00,original,brier_not_improved,0.352941,0.487805,0.537805,0.452941,selected,0.305818,True,0.470588,0.517857,29,56,46
10,lightgbm,2020-12_t1,1,lightgbm_02,original,brier_not_improved,0.000000,0.636364,0.686364,0.100000,selected,0.251216,True,0.500000,0.659091,29,44,41
11,lightgbm,2020-12_t2,2,lightgbm_00,sigmoid,brier_improved,0.214286,0.631579,0.681579,0.314286,selected,0.374194,True,0.500000,0.675000,27,40,21
12,lightgbm,2022-12_t1,1,lightgbm_01,original,brier_not_improved,0.000000,0.500000,0.550000,0.100000,selected,0.273505,True,0.200000,0.511111,23,45,49
13,lightgbm,2022-12_t2,2,lightgbm_00,original,brier_not_improved,0.266667,0.550000,0.600000,0.366667,selected,0.229855,True,0.666667,0.571429,36,63,66
14,lightgbm,2024-06_t1,1,lightgbm_01,original,brier_not_improved,0.000000,0.275862,0.325862,0.100000,selected,0.284423,True,0.411765,0.300000,30,100,102
15,lightgbm,2024-06_t2,2,lightgbm_01,original,brier_not_improved,0.294118,0.308642,0.358642,0.394118,selected,0.269266,True,0.705882,0.348624,38,109,109
16,gam,2018-12_t1,1,gam_02,original,brier_not_improved,0.000000,0.409091,0.459091,0.100000,selected,0.365831,True,0.294118,0.423077,22,52,45
17,gam,2018-12_t2,2,gam_02,original,brier_not_improved,0.352941,0.487805,0.537805,0.452941,selected,0.356292,False,0.411765,0.509434,27,53,21
18,gam,2020-12_t1,1,gam_02,original,brier_not_improved,0.000000,0.636364,0.686364,0.100000,selected,0.309454,True,0.285714,0.657143,23,35,36
19,gam,2020-12_t2,2,gam_01,sigmoid,brier_improved,0.214286,0.631579,0.681579,0.314286,selected,0.442928,True,0.428571,0.500000,10,20,29
20,gam,2022-12_t1,1,gam_00,original,brier_not_improved,0.000000,0.500000,0.550000,0.100000,selected,0.303453,True,0.200000,0.531915,25,47,51
21,gam,2022-12_t2,2,gam_01,original,brier_not_improved,0.266667,0.550000,0.600000,0.366667,selected,0.181599,True,0.666667,0.600000,42,70,65
22,gam,2024-06_t1,1,gam_03,original,brier_not_improved,0.000000,0.275862,0.325862,0.100000,selected,0.377125,True,0.352941,0.288660,28,97,103
23,gam,2024-06_t2,2,gam_03,original,brier_not_improved,0.294118,0.308642,0.358642,0.394118,selected,0.215989,True,0.764706,0.348624,38,109,111

,candidate,window_id,horizon,selected_configuration_id,chronology_pass,independence_pass,component_available_pass,no_reserved_pass
0,xgboost,2018-12_t1,1,xgboost_00,True,True,True,True
1,xgboost,2018-12_t2,2,xgboost_00,True,True,True,True
2,xgboost,2020-12_t1,1,xgboost_02,True,True,True,True
3,xgboost,2020-12_t2,2,xgboost_00,True,True,True,True
4,xgboost,2022-12_t1,1,xgboost_04,True,True,True,True
5,xgboost,2022-12_t2,2,xgboost_02,True,True,True,True
6,xgboost,2024-06_t1,1,xgboost_01,True,True,True,True
7,xgboost,2024-06_t2,2,xgboost_01,True,True,True,True
8,lightgbm,2018-12_t1,1,lightgbm_00,True,True,True,True
9,lightgbm,2018-12_t2,2,lightgbm_00,True,True,True,True
10,lightgbm,2020-12_t1,1,lightgbm_02,True,True,True,True
11,lightgbm,2020-12_t2,2,lightgbm_00,True,True,True,True
12,lightgbm,2022-12_t1,1,lightgbm_01,True,True,True,True
13,lightgbm,2022-12_t2,2,lightgbm_00,True,True,True,True
14,lightgbm,2024-06_t1,1,lightgbm_01,True,True,True,True
15,lightgbm,2024-06_t2,2,lightgbm_01,True,True,True,True
16,gam,2018-12_t1,1,gam_02,True,True,True,True
17,gam,2018-12_t2,2,gam_02,True,True,True,True
18,gam,2020-12_t1,1,gam_02,True,True,True,True
19,gam,2020-12_t2,2,gam_01,True,True,True,True
20,gam,2022-12_t1,1,gam_00,True,True,True,True
21,gam,2022-12_t2,2,gam_01,True,True,True,True
22,gam,2024-06_t1,1,gam_03,True,True,True,True
23,gam,2024-06_t2,2,gam_03,True,True,True,True

In [5]:
posterior = pd.read_csv(result.bundle / "posterior_metrics.csv")
independent_checks = pd.read_csv(result.bundle / "independent_checks.csv")

window_means = (
    posterior[
        posterior["metric"].isin(
            ["average_precision", "brier", "onset_sensitivity", "false_alarm_ratio"]
        )
    ]
    .groupby(["candidate", "horizon", "metric"], dropna=False)["value"]
    .mean()
    .reset_index()
)
display(window_means)

display(
    independent_checks[
        ["candidate", "window_id", "horizon", "check", "pass"]
    ].sort_values(["candidate", "window_id", "horizon", "check"])
)

failed = independent_checks[~independent_checks["pass"].fillna(False)]
print(f"Independent checks failing rows: {failed.shape[0]}")
print("Stage 5 delivery 1 remains development evidence only; no champion and no reserved-block evaluation.")

      candidate  horizon             metric     value
0           gam        1  average_precision  0.714353
1           gam        1              brier  0.157943
2           gam        1  false_alarm_ratio  0.370576
3           gam        1  onset_sensitivity  0.174722
4           gam        2  average_precision  0.657009
5           gam        2              brier  0.201318
6           gam        2  false_alarm_ratio  0.403315
7           gam        2  onset_sensitivity  0.431689
8      lightgbm        1  average_precision  0.724353
9      lightgbm        1              brier  0.149082
10     lightgbm        1  false_alarm_ratio  0.394576
11     lightgbm        1  onset_sensitivity  0.291940
12     lightgbm        2  average_precision  0.664200
13     lightgbm        2              brier  0.192675
14     lightgbm        2  false_alarm_ratio  0.410519
15     lightgbm        2  onset_sensitivity  0.406414
16  persistence        1  average_precision  0.581263
17  persistence        1              brier       NaN
18  persistence        1  false_alarm_ratio  0.324453
19  persistence        1  onset_sensitivity  0.000000
20  persistence        2  average_precision  0.546259
21  persistence        2              brier       NaN
22  persistence        2  false_alarm_ratio  0.363612
23  persistence        2  onset_sensitivity  0.205154
24      xgboost        1  average_precision  0.728097
25      xgboost        1              brier  0.150007
26      xgboost        1  false_alarm_ratio  0.364294
27      xgboost        1  onset_sensitivity  0.170795
28      xgboost        2  average_precision  0.657787
29      xgboost        2              brier  0.193520
30      xgboost        2  false_alarm_ratio  0.402555
31      xgboost        2  onset_sensitivity  0.351206

,candidate,window_id,horizon,check,pass
162,gam,2018-12_t1,1,component_availability_vs_external_origin,True
165,gam,2018-12_t1,1,internal_origin_transition_calibration_fit_to_...,True
166,gam,2018-12_t1,1,internal_origin_transition_calibration_selecti...,True
164,gam,2018-12_t1,1,internal_origin_transition_hp_to_calibration_fit,True
167,gam,2018-12_t1,1,internal_origin_transition_threshold_to_external,True
...,...,...,...,...,...
78,xgboost,2024-06_t2,2,no_reserved_block_access,True
79,xgboost,2024-06_t2,2,posterior_counts_recomputed,True
71,xgboost,2024-06_t2,2,selection_independence,True
73,xgboost,2024-06_t2,2,target_origin_lag_matches_horizon,True
70,xgboost,2024-06_t2,2,threshold_selection_counts,True

Independent checks failing rows: 0
Stage 5 delivery 1 remains development evidence only; no champion and no reserved-block evaluation.